/**
 * generated by Xtext 2.20.0
 */
package org.example.rules.ui.contentassist;

import org.example.rules.ui.contentassist.AbstractRulesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RulesProposalProvider extends AbstractRulesProposalProvider {
}
