/**
 * generated by Xtext 2.20.0
 */
package org.example.rules.model;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.rules.model.ActionRef#getNode <em>Node</em>}</li>
 * </ul>
 *
 * @see org.example.rules.model.ModelPackage#getActionRef()
 * @model
 * @generated
 */
public interface ActionRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' reference.
   * @see #setNode(Action)
   * @see org.example.rules.model.ModelPackage#getActionRef_Node()
   * @model
   * @generated
   */
  Action getNode();

  /**
   * Sets the value of the '{@link org.example.rules.model.ActionRef#getNode <em>Node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' reference.
   * @see #getNode()
   * @generated
   */
  void setNode(Action value);

} // ActionRef
