/**
 * generated by Xtext 2.20.0
 */
package org.example.rules.model;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.rules.model.Rule#getName <em>Name</em>}</li>
 *   <li>{@link org.example.rules.model.Rule#getFilters <em>Filters</em>}</li>
 *   <li>{@link org.example.rules.model.Rule#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see org.example.rules.model.ModelPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.rules.model.ModelPackage#getRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.rules.model.Rule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Filters</b></em>' containment reference list.
   * The list contents are of type {@link org.example.rules.model.Filter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filters</em>' containment reference list.
   * @see org.example.rules.model.ModelPackage#getRule_Filters()
   * @model containment="true"
   * @generated
   */
  EList<Filter> getFilters();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.example.rules.model.ActionRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see org.example.rules.model.ModelPackage#getRule_Actions()
   * @model containment="true"
   * @generated
   */
  EList<ActionRef> getActions();

} // Rule
