/*
 * generated by Xtext 2.20.0
 */
package org.example.rules.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.example.rules.ui.internal.RulesActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RulesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RulesActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RulesActivator activator = RulesActivator.getInstance();
		return activator != null ? activator.getInjector(RulesActivator.ORG_EXAMPLE_RULES_RULES) : null;
	}

}
