/**
 * generated by Xtext 2.20.0
 */
package org.example.rules.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.example.rules.ui.AbstractRulesUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RulesUiModule extends AbstractRulesUiModule {
  public RulesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
