/**
 * generated by Xtext 2.20.0
 */
package org.example.rules.ide;

import org.example.rules.ide.AbstractRulesIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RulesIdeModule extends AbstractRulesIdeModule {
}
