/*
 * generated by Xtext 2.20.0
 */
package org.example.rules.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRulesScopeProvider extends DelegatingScopeProvider {
}
