/*
 * generated by Xtext 2.20.0
 */
package org.example.rules.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.example.rules.ui.internal.RulesActivator;

public class RulesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RulesActivator.getInstance().getInjector("org.example.rules.Rules");
	}

}
